(()=>{'use strict';
const $=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),uid=()=>crypto.randomUUID?.()||('id'+Date.now()+Math.random());
function today(){let d=new Date();return [d.getFullYear(),String(d.getMonth()+1).padStart(2,'0'),String(d.getDate()).padStart(2,'0')].join('-')}
function dateOK(s){if(!/^\d{4}-\d{2}-\d{2}$/.test(s))return false;let [y,m,d]=s.split('-').map(Number);let x=new Date(0);x.setUTCFullYear(y,m-1,d);return y>=1900&&x.getUTCFullYear()===y&&x.getUTCMonth()===m-1&&x.getUTCDate()===d}
function shiftDay(s,n){let [y,m,d]=s.split('-').map(Number),x=new Date(0);x.setUTCFullYear(y,m-1,d+n);return x.toISOString().slice(0,10)}
function num(v,min=0,max=999999,dec=2){let s=String(v??'').trim();if(!/^\d+(?:\.\d{1,2})?$/.test(s))return NaN;let n=Number(s);return n>=min&&n<=max&&Math.round(n*10**dec)===n*10**dec?n:NaN}
const themes={Ivory:{bg:'#f6f5ee',surface:'#fffefa',surface2:'#e7f2eb',ink:'#173b36',muted:'#526962',line:'#cbd9d1',accent:'#1c6258',accentText:'#fff',peach:'#f4c8b4',chart:'#3a8e7c',danger:'#a2323e',dangerText:'#fff'},Sage:{bg:'#eef3ed',surface:'#fcfefb',surface2:'#ddece2',ink:'#18392e',muted:'#4b6657',line:'#bdd3c3',accent:'#285e45',accentText:'#fff',peach:'#edc6a9',chart:'#367b55',danger:'#a2323e',dangerText:'#fff'},Peach:{bg:'#fff4ed',surface:'#fffdf9',surface2:'#fbe8dc',ink:'#48342d',muted:'#68554b',line:'#e4cdbd',accent:'#775039',accentText:'#fff',peach:'#e9aa89',chart:'#976249',danger:'#9b303a',dangerText:'#fff'},Lilac:{bg:'#f5f2f9',surface:'#fffefe',surface2:'#eae3f1',ink:'#352c44',muted:'#60556d',line:'#d1c6dc',accent:'#614878',accentText:'#fff',peach:'#e9b7ad',chart:'#8561a1',danger:'#9b303a',dangerText:'#fff'},Midnight:{bg:'#101b20',surface:'#1c2b31',surface2:'#263b40',ink:'#f5f8f6',muted:'#d1e0da',line:'#607b7d',accent:'#91e0cb',accentText:'#102623',peach:'#ffc6a8',chart:'#a2e8d4',danger:'#ffb3b4',dangerText:'#301114'}};
const defaults={theme:'Ivory',customThemes:{},font:'modern',density:'comfortable',card:'rounded',layout:'standard',contrast:false,weightUnit:'kg',lengthUnit:'cm',accent:'#1c6258'};
const kinds=['weights','measurements','workouts','goals','habits','checks','milestones','notes'];
const blank=()=>({version:1,profile:{name:'',startKg:0,goalKg:0,startDate:today(),deadline:''},settings:structuredClone(defaults),data:Object.fromEntries(kinds.map(k=>[k,[]]))});
let state=blank(),db,saveQueue=Promise.resolve(),view='dashboard',search='',weekStart='',editing=null,focusBack=null,confirmResolve=null,searchTimer,toastTimer;
const DB=window.DEMO_MODE===true?'harbornest-motion-milestones-demo-v1':'harbornest-motion-milestones-customer-v1';
function openDB(){return new Promise((res,rej)=>{let r=indexedDB.open(DB,1);r.onupgradeneeded=()=>r.result.createObjectStore('state');r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)})}
function load(){return new Promise((res,rej)=>{let r=db.transaction('state','readonly').objectStore('state').get('app');r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)})}
function write(x){return new Promise((res,rej)=>{let tx=db.transaction('state','readwrite');tx.objectStore('state').put(x,'app');tx.oncomplete=res;tx.onerror=()=>rej(tx.error)})}
function save(){let x=structuredClone(state);saveQueue=saveQueue.catch(()=>{}).then(()=>write(x)).catch(()=>toast('Saving failed. Download a backup.'))}
function validState(x){return x&&x.version===1&&x.profile&&x.settings&&x.data&&kinds.every(k=>Array.isArray(x.data[k])&&x.data[k].length<50000&&x.data[k].every(r=>r&&typeof r.id==='string'&&Object.values(r).every(v=>typeof v!=='number'||Number.isFinite(v))))}
function toast(s){let e=$('#toast');e.textContent=s;e.hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>e.hidden=true,3500)}
function ask(s){focusBack=document.activeElement;$('#confirmText').textContent=s;$('#confirmDialog').showModal();return new Promise(r=>confirmResolve=r)}
function confirmClose(v){$('#confirmDialog').close();confirmResolve?.(v);confirmResolve=null;focusBack?.focus?.()}
function displayWeight(kg){return state.settings.weightUnit==='lb'?(kg*2.2046226218).toFixed(1)+' lb':Number(kg).toFixed(1)+' kg'}
function inputWeight(kg){return state.settings.weightUnit==='lb'?(kg*2.2046226218).toFixed(1):Number(kg||0).toFixed(1)}
function toKg(v){let n=num(v,0,2000,1);return Number.isFinite(n)?Math.round((state.settings.weightUnit==='lb'?n/2.2046226218:n)*100)/100:NaN}
function displayLength(cm){return state.settings.lengthUnit==='in'?(cm/2.54).toFixed(1)+' in':Number(cm).toFixed(1)+' cm'}
function inputLength(cm){return state.settings.lengthUnit==='in'?(cm/2.54).toFixed(1):Number(cm||0).toFixed(1)}
function toCm(v){let n=num(v,0,1000,1);return Number.isFinite(n)?Math.round((state.settings.lengthUnit==='in'?n*2.54:n)*100)/100:NaN}
function stamp(s){return dateOK(s)?new Date(s+'T12:00:00Z').toLocaleDateString(undefined,{day:'numeric',month:'short',year:'numeric',timeZone:'UTC'}):'—'}
function pct(n,d){return d>0?Math.max(0,Math.min(100,Math.round(n/d*100))):0}
function weights(){return state.data.weights.map((r,i)=>({...r,_order:i})).sort((a,b)=>a.date.localeCompare(b.date)||a._order-b._order)}
function currentKg(){return weights().at(-1)?.kg||state.profile.startKg||0}
function weekOf(s){let [y,m,d]=s.split('-').map(Number),x=new Date(Date.UTC(y,m-1,d));return shiftDay(s,-((x.getUTCDay()+6)%7))}
function workoutsWeek(start=weekOf(today())){return state.data.workouts.filter(x=>x.date>=start&&x.date<=shiftDay(start,6))}
function streak(){let dates=new Set(state.data.workouts.map(x=>x.date));let n=0,d=today();if(!dates.has(d))d=shiftDay(d,-1);while(dates.has(d)){n++;d=shiftDay(d,-1)}return n}
function summary(){let start=state.profile.startKg||weights()[0]?.kg||0,now=currentKg(),goal=state.profile.goalKg,delta=start-now,range=Math.abs(start-goal),progress=range&&start!==goal?pct(start>goal?start-now:now-start,range):goal&&now===goal?100:0;let wk=workoutsWeek(),done=state.data.checks.filter(x=>x.date>=weekOf(today())&&x.date<=shiftDay(weekOf(today()),6)).length,daysElapsed=Math.min(7,Math.max(1,Math.round((new Date(today()+'T12:00:00Z')-new Date(weekOf(today())+'T12:00:00Z'))/86400000)+1)),total=state.data.habits.length*daysElapsed;return {start,now,goal,delta,progress,workouts:wk.length,minutes:wk.reduce((a,x)=>a+x.minutes,0),streak:streak(),consistency:total?pct(done,total):0}}
function trend(values,labels,unit=''){if(!values.length)return '<div class="empty">Log entries to see your trend.</div>';let min=Math.min(...values),max=Math.max(...values),range=Math.max(1,max-min),pts=values.map((v,i)=>[25+i*750/Math.max(values.length-1,1),205-(v-min)/range*155]);let path=pts.map(([x,y],i)=>(i?'L':'M')+x.toFixed(1)+' '+y.toFixed(1)).join(' ');return '<svg class="chart" viewBox="0 0 800 240" role="img" aria-label="Trend from '+esc(labels[0]||'first')+' to '+esc(labels.at(-1)||'last')+'"><path d="M25 218H775" stroke="var(--line)" stroke-width="2"/><path d="'+path+'" fill="none" stroke="var(--chart)" stroke-width="4"/>'+pts.map(([x,y],i)=>'<circle cx="'+x+'" cy="'+y+'" r="5" fill="var(--accent)"><title>'+esc(labels[i])+': '+values[i].toFixed(1)+' '+esc(unit)+'</title></circle>').join('')+'</svg><p class="chart-note">First '+values[0].toFixed(1)+' '+esc(unit)+' · Latest '+values.at(-1).toFixed(1)+' '+esc(unit)+'</p>'}
function bar(x,y){let p=pct(x,y);return '<div class="progress" role="progressbar" aria-valuenow="'+p+'" aria-valuemin="0" aria-valuemax="100"><i style="width:'+p+'%"></i></div>'}
function donut(n){return '<div class="donut" style="--pct:'+n+'%"><span>'+n+'%</span></div>'}
function stat(rows){return '<div class="stats">'+rows.map(([l,v,h])=>'<div class="stat"><span class="label">'+esc(l)+'</span><strong>'+esc(v)+'</strong><span class="hint">'+esc(h||'')+'</span></div>').join('')+'</div>'}
function title(k,sub,actions=''){return '<div class="sectionhead"><div><small class="eyebrow">'+esc(k.toUpperCase())+'</small><h1>'+esc(k)+'</h1><p>'+esc(sub)+'</p></div><div class="toolbar">'+actions+'</div></div>'}
function actions(kind,r){return '<div class="record-actions"><button class="smallbtn" data-edit="'+kind+'" data-id="'+esc(r.id)+'" aria-label="Edit record">Edit</button><button class="smallbtn" data-delete="'+kind+'" data-id="'+esc(r.id)+'" aria-label="Delete record">Delete</button></div>'}
function download(blob,name){let a=document.createElement('a'),url=URL.createObjectURL(blob);a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
function csvCell(v){let s=String(v??'');if(/^[=+\-@\t\r]/.test(s))s="'"+s;return '"'+s.replaceAll('"','""')+'"'}
function csv(rows,name){download(new Blob([rows.map(r=>r.map(csvCell).join(',')).join('\r\n')],{type:'text/csv;charset=utf-8'}),name)}

const groups=[['OVERVIEW',[['dashboard','Dashboard','◉'],['weight','Weight progress','◌'],['measurements','Body measurements','▤']]],['MOVE',[['workouts','Workout log','✧'],['habits','Weekly habits','▦'],['goals','Fitness goals','◎']]],['REFLECT',[['milestones','Milestones & badges','✦'],['notes','Progress notes','☷'],['insights','Insights & reports','▥']]],['SYSTEM',[['settings','Customize & backup','⚙']]]];
const labels=Object.fromEntries(groups.flatMap(([,a])=>a.map(([k,v])=>[k,v])));
function nav(){let h='';for(let [g,a] of groups){h+='<div class="navgroup">'+g+'</div>';for(let [k,l,ic] of a)h+='<button class="navitem '+(k===view?'active':'')+'" data-nav="'+k+'"><span class="navicon">'+ic+'</span>'+esc(l)+'</button>'}$('#nav').innerHTML=h;$('#mobileNav').innerHTML=[['dashboard','Home','◉'],['weight','Weight','◌'],['workouts','Workouts','✧'],['habits','Habits','▦'],['settings','Settings','⚙']].map(([k,l,i])=>'<button data-nav="'+k+'" class="'+(k===view?'active':'')+'"><b>'+i+'</b>'+l+'</button>').join('')}
function appearance(){let s=state.settings,t=themes[s.theme]||s.customThemes[s.theme]||themes.Ivory;for(let k of ['bg','surface','surface2','ink','muted','line','accent','accentText','peach','chart','danger','dangerText'])document.documentElement.style.setProperty('--'+k,t[k]);for(let k of ['theme','font','density','card','layout','contrast'])document.body.dataset[k]=s[k];document.querySelector('meta[name="theme-color"]').content=t.accent}
function navigate(k){view=k;search='';nav();$('#pageTitle').textContent=labels[k]||'Planner';renderView();$('.sidebar').classList.remove('open');$('#menuBtn').setAttribute('aria-expanded','false');window.scrollTo(0,0)}
function dashboard(){
 let s=summary(),w=weights(),recent=state.data.workouts.slice().sort((a,b)=>b.date.localeCompare(a.date)).slice(0,3);
 if(!state.profile.startKg&&!w.length)return '<section class="hero"><div><small class="eyebrow">WELCOME TO MOTION & MILESTONES</small><h1>Start with where you are.</h1><p>Set a starting point, choose a personal goal, then log the moments that matter. The journal meets you at your pace.</p><button class="primary" data-profile="1">Set up your journey</button></div><div class="hero-aside"><span>Your records</span><strong>Private and local</strong><span>No account required.</span></div></section><div class="grid"><div class="panel"><h2>Three simple steps</h2><p>Set your starting point · Log a workout or weight entry · Look back at your progress.</p></div><div class="panel"><h2>More than a number</h2><p>Measurements, movement, habits and reflections all count.</p></div></div>';
 let badges=earned().filter(x=>x[1]).slice(0,3),recentHTML=recent.length?recent.map(x=>'<div class="record"><div><b>'+esc(x.type)+'</b><div class="meta">'+stamp(x.date)+' · '+x.minutes+' min · '+esc(x.intensity)+'</div></div></div>').join(''):'<div class="empty">No workouts logged.</div>';
 return '<section class="hero"><div><small class="eyebrow">YOUR MOVEMENT JOURNAL</small><h1>Progress is a collection of moments.</h1><p>'+esc(state.profile.name||'Your journey')+' · '+s.workouts+' workouts this week · '+s.streak+' day movement streak</p><button class="primary" data-add="workouts">+ Log a workout</button> <button class="quiet" data-add="weights">+ Log weight</button></div><div class="hero-aside"><span>Current recorded weight</span><strong>'+displayWeight(s.now)+'</strong><span>From '+displayWeight(s.start)+' · Goal '+(s.goal?displayWeight(s.goal):'Not set')+'</span></div></section>'+
 stat([['Weight change',displayWeight(Math.abs(s.delta)),s.delta>0?'Down from start':s.delta<0?'Up from start':'At starting point'],['Workouts this week',String(s.workouts),s.minutes+' minutes logged'],['Movement streak',s.streak+' days','Consecutive workout days'],['Habit consistency',s.consistency+'%','Checks this week']])+
 '<div class="cols"><div class="panel"><h2>Your goal progress</h2>'+donut(s.progress)+'<p class="muted">From your recorded start toward your chosen goal.</p>'+bar(s.progress,100)+'<p>Personal target date: <strong>'+(state.profile.deadline?stamp(state.profile.deadline):'Not set')+'</strong></p></div><div class="panel"><h2>Weight trend</h2>'+trend(w.slice(-10).map(x=>state.settings.weightUnit==='lb'?x.kg*2.2046226218:x.kg),w.slice(-10).map(x=>stamp(x.date)),state.settings.weightUnit)+'</div></div>'+
 '<div class="cols" style="margin-top:18px"><div class="panel"><div class="panelhead"><h2>Recent movement</h2><button class="smallbtn" data-nav="workouts">View log</button></div>'+recentHTML+'</div><div class="panel"><h2>Progress badges</h2>'+(badges.length?badges.map(x=>'<span class="pill">'+esc(x[0])+'</span> ').join(''):'<p class="muted">Your first badge appears after your first workout or weight check-in.</p>')+'<p>Choose one small action to revisit today.</p><button class="quiet" data-nav="habits">Open weekly habits</button></div></div>';
}
function filterRows(kind){return state.data[kind].filter(x=>!search||JSON.stringify(x).toLowerCase().includes(search.toLowerCase())).slice().sort((a,b)=>(b.date||'').localeCompare(a.date||''))}
function recordList(kind,renderer){let rows=filterRows(kind);return rows.map(r=>renderer(r)+actions(kind,r)+'</article>').join('')||'<div class="empty">No matching entries yet.</div>'}
function weightView(){let w=weights(),s=summary();return title('Weight progress','Log at your own pace and see the trend.','<button class="primary" data-add="weights">+ Add weight</button><button class="quiet" data-csv="weights">CSV</button>')+stat([['Starting',s.start?displayWeight(s.start):'—'],['Current',s.now?displayWeight(s.now):'—'],['Goal',s.goal?displayWeight(s.goal):'—'],['Change',s.start?displayWeight(Math.abs(s.delta)):'—',s.delta>0?'Down':s.delta<0?'Up':'Stable']])+'<div class="panel"><h2>Weight over time</h2>'+trend(w.map(x=>state.settings.weightUnit==='lb'?x.kg*2.2046226218:x.kg),w.map(x=>stamp(x.date)),state.settings.weightUnit)+'</div><div class="toolbar"><input id="listSearch" type="search" aria-label="Search weight entries" placeholder="Search dates or notes" value="'+esc(search)+'"></div><div id="listContainer">'+recordList('weights',r=>'<article class="record"><div><h3>'+displayWeight(r.kg)+'</h3><div class="meta">'+stamp(r.date)+'</div><p>'+esc(r.notes||'')+'</p></div>')+'</div>'}
const measureKeys=['waist','hips','chest','arms','thighs','shoulders'];
function measurementView(){let rows=filterRows('measurements'),last=rows[0];return title('Body measurements','Notice changes beyond the scale.','<button class="primary" data-add="measurements">+ Log measurements</button><button class="quiet" data-csv="measurements">CSV</button>')+'<div class="panel"><h2>Latest measurements</h2><div class="measure-bars">'+(last?measureKeys.map(k=>'<div class="measure-row"><b>'+k[0].toUpperCase()+k.slice(1)+'</b>'+bar(last[k],Math.max(...measureKeys.map(x=>last[x]),1))+'<span>'+displayLength(last[k])+'</span></div>').join(''):'<div class="empty">Add a measurement set to begin.</div>')+'</div></div><div class="toolbar"><input id="listSearch" type="search" value="'+esc(search)+'" placeholder="Search measurement entries" aria-label="Search measurements"></div><div id="listContainer">'+recordList('measurements',r=>'<article class="record"><div><h3>'+stamp(r.date)+'</h3><div class="meta">'+measureKeys.map(k=>k+': '+displayLength(r[k])).join(' · ')+'</div><p>'+esc(r.notes||'')+'</p></div>')+'</div>'}
function workoutView(){let rows=filterRows('workouts'),mins=rows.reduce((a,x)=>a+x.minutes,0),cal=rows.reduce((a,x)=>a+x.calories,0);return title('Workout log','Every session counts, from a walk to strength training.','<button class="primary" data-add="workouts">+ Log workout</button><button class="quiet" data-csv="workouts">CSV</button>')+stat([['Sessions',rows.length],['Minutes',mins],['Estimated calories',cal,'Optional self-reported field'],['This week',workoutsWeek().length]])+'<div class="toolbar"><input id="listSearch" type="search" value="'+esc(search)+'" placeholder="Search type, notes or date" aria-label="Search workouts"></div><div id="listContainer">'+recordList('workouts',r=>'<article class="record"><div><h3>'+esc(r.type)+'</h3><div class="meta">'+stamp(r.date)+' · '+r.minutes+' min · '+esc(r.intensity)+' · '+r.calories+' kcal entered</div><p>'+esc(r.notes||'')+'</p></div>')+'</div>'}
function habitsView(){let start=weekStart||weekOf(today()),days=Array.from({length:7},(_,i)=>shiftDay(start,i));let h=title('Weekly habits','Tap a day to mark it complete. Checkmarks save immediately.','<button class="primary" data-add="habits">+ Create habit</button>');h+='<div class="panel"><div class="panelhead"><h2>Week of '+stamp(start)+'</h2><div><button class="smallbtn" data-week="-7" aria-label="Previous week">←</button> <button class="smallbtn" data-week="7" aria-label="Next week">→</button></div></div><div class="habit-table"><div class="habit-grid"><b class="habit-name">Habit</b>'+days.map(d=>'<b>'+new Date(d+'T12:00:00Z').toLocaleDateString(undefined,{weekday:'short',timeZone:'UTC'})+'<br>'+d.slice(8)+'</b>').join('');for(let habit of state.data.habits){h+='<span class="habit-name">'+esc(habit.name)+'<br><small>'+esc(habit.unit||'Daily')+'</small>'+actions('habits',habit)+'</span>';for(let day of days){let done=state.data.checks.some(x=>x.habitId===habit.id&&x.date===day);h+='<button class="habit-check '+(done?'done':'')+'" data-check="'+esc(habit.id)+'" data-date="'+day+'" aria-label="'+(done?'Unmark':'Mark')+' '+esc(habit.name)+' on '+day+'" aria-pressed="'+done+'">'+(done?'✓':'○')+'</button>'}}h+='</div></div></div><div class="panel"><h2>This week in view</h2><p>'+state.data.checks.filter(x=>x.date>=start&&x.date<=days[6]).length+' completed checks across '+state.data.habits.length+' habits.</p></div>';return h}
function goalsView(){let rows=filterRows('goals');return title('Fitness goals','Choose goals that feel meaningful to you.','<button class="primary" data-add="goals">+ Add goal</button>')+'<div class="panel">'+(rows.map(r=>'<article class="record"><div><small class="eyebrow">'+esc(r.category)+'</small><h3>'+esc(r.name)+'</h3><div class="meta">'+(r.deadline?stamp(r.deadline):'No deadline')+' · '+esc(r.status)+'</div>'+bar(r.current,r.target)+'<p>'+r.current+' / '+r.target+' '+esc(r.unit||'')+' · '+esc(r.notes||'')+'</p></div>'+actions('goals',r)+'</article>').join('')||'<div class="empty">Set a goal to track a meaningful change.</div>')+'</div>'}
function earned(){let s=summary(),n=state.data.workouts.length,loss=Math.max(0,s.delta);return [['First step',n>=1,'Record one workout'],['Five sessions',n>=5,'Record five workouts'],['Ten sessions',n>=10,'Record ten workouts'],['Seven day streak',s.streak>=7,'Move on seven consecutive days'],['First check-in',state.data.weights.length>=1,'Log your weight'],['2 kg milestone',loss>=2,'Recorded weight down 2 kg'],['Goal reached',s.goal>0&&s.progress>=100,'Reach the recorded weight goal']]}
function milestonesView(){let a=earned();return title('Milestones & badges','Celebrate what you have recorded, big or small.','<button class="primary" data-add="milestones">+ Add personal win</button>')+'<div class="panel"><h2>Automatic badges</h2><div class="badge-grid">'+a.map(([name,yes,sub])=>'<div class="award '+(yes?'':'locked')+'"><b>'+(yes?'✦':'○')+'</b><strong>'+esc(name)+'</strong><p>'+esc(sub)+'</p></div>').join('')+'</div></div><div class="panel"><h2>Personal milestones</h2>'+recordList('milestones',r=>'<article class="record"><div><h3>'+esc(r.name)+'</h3><div class="meta">'+stamp(r.date)+'</div><p>'+esc(r.notes||'')+'</p></div>')+'</div>'}
function notesView(){return title('Progress notes','Reflect on feelings, confidence and what you notice. Photo notes are text only.','<button class="primary" data-add="notes">+ Write note</button>')+'<div class="toolbar"><input id="listSearch" type="search" value="'+esc(search)+'" placeholder="Search reflections" aria-label="Search notes"></div><div id="listContainer">'+recordList('notes',r=>'<article class="record"><div><h3>'+esc(r.name)+'</h3><div class="meta">'+stamp(r.date)+' · Confidence '+r.confidence+'/5'+(r.photoNote?' · Photo note (text)':'')+'</div><p>'+esc(r.notes||'')+'</p><p class="muted">'+esc(r.photoNote||'')+'</p></div>')+'</div>'}
function insightsView(){let s=summary(),w=weights(),weeks=Array.from({length:8},(_,i)=>shiftDay(weekOf(today()),(i-7)*7)),counts=weeks.map(day=>workoutsWeek(day).length);return title('Insights & reports','A record-based overview of your movement and check-ins.','<button class="quiet" data-print="1">Print summary</button><button class="quiet" data-csv="workouts">Workout CSV</button>')+stat([['Current',s.now?displayWeight(s.now):'—'],['Sessions logged',state.data.workouts.length],['This week',s.workouts+' workouts'],['Habits checked',s.consistency+'%']])+'<div class="cols"><div class="panel"><h2>Weekly workouts</h2>'+trend(counts,weeks.map(stamp),'sessions')+'</div><div class="panel"><h2>Weight check-ins</h2>'+trend(w.map(x=>state.settings.weightUnit==='lb'?x.kg*2.2046226218:x.kg),w.map(x=>stamp(x.date)),state.settings.weightUnit)+'</div></div><p class="disclaimer">These charts describe entered records only. They do not diagnose health or prescribe exercise.</p>'}

function settingsView(){let s=state.settings,p=state.profile;return title('Customize & backup','Make the journal comfortable for your eyes and your routine.')+'<div class="cols"><div class="panel"><h2>Your starting point</h2><div class="form-grid"><label>Name or nickname<input id="profileName" maxlength="60" value="'+esc(p.name)+'"></label><label>Starting weight ('+s.weightUnit+')<input id="profileStart" type="number" step=".1" min="0" value="'+(p.startKg?inputWeight(p.startKg):'')+'"></label><label>Goal weight ('+s.weightUnit+')<input id="profileGoal" type="number" step=".1" min="0" value="'+(p.goalKg?inputWeight(p.goalKg):'')+'"></label><label>Start date<input id="profileDate" type="date" value="'+esc(p.startDate)+'"></label><label>Personal target date<input id="profileDeadline" type="date" value="'+esc(p.deadline)+'"></label></div><button id="saveProfile" class="primary">Save starting point</button><p class="muted">A target date is optional. Your progress is yours to define.</p></div><div class="panel"><h2>Theme collection</h2><div class="theme-grid">'+Object.entries({...themes,...s.customThemes}).map(([name,t])=>'<button class="theme-tile '+(s.theme===name?'selected':'')+'" data-theme-choice="'+esc(name)+'" aria-pressed="'+(s.theme===name)+'"><i style="background:'+esc(t.bg)+';border-color:'+esc(t.accent)+'"><b style="background:'+esc(t.accent)+'"></b></i><span>'+esc(name)+'</span></button>').join('')+'</div><label>Custom accent<input id="customAccent" type="color" value="'+esc(s.accent)+'"></label><button id="saveCustomTheme" class="quiet">Save custom theme</button></div></div><div class="cols"><div class="panel"><h2>Units and display</h2><div class="form-grid">'+[['weightUnit',['kg','lb']],['lengthUnit',['cm','in']],['font',['modern','editorial']],['density',['compact','comfortable','spacious']],['card',['rounded','square']],['layout',['standard','wide']]].map(([k,opts])=>'<label>'+k+'<select data-setting="'+k+'">'+opts.map(x=>'<option value="'+x+'" '+(s[k]===x?'selected':'')+'>'+x+'</option>').join('')+'</select></label>').join('')+'</div><label class="check"><input type="checkbox" data-setting="contrast" '+(s.contrast?'checked':'')+'> Extra contrast</label><button id="appearanceReset" class="quiet">Restore default appearance</button><p class="muted">Changing units converts display and new input; saved measurements retain canonical kg and cm values.</p></div><div class="panel"><h2>Backup & privacy</h2><p>Records save automatically in this browser. There is no account or automatic device sync. Download a JSON backup before clearing browser data or moving devices.</p><div class="toolbar"><button id="backupBtn" class="quiet">Download JSON backup</button><button id="restoreBtn" class="quiet">Restore JSON</button><button data-csv="weights" class="quiet">Weight CSV</button><button data-csv="measurements" class="quiet">Measurements CSV</button><button id="resetBtn" class="danger">Erase local records</button></div></div></div>'}
function renderView(){let fn={dashboard,weight:weightView,measurements:measurementView,workouts:workoutView,habits:habitsView,goals:goalsView,milestones:milestonesView,notes:notesView,insights:insightsView,settings:settingsView}[view]||dashboard;$('#view').innerHTML=fn()}
const F=(k,l,type='text',required=false,choices='')=>({k,l,type,required,choices});
const defs={
 weights:{name:'Weight entry',fields:[F('date','Date','date',true),F('kg','Weight','weight',true),F('notes','Notes','textarea')]},
 measurements:{name:'Measurement set',fields:[F('date','Date','date',true),...measureKeys.map(k=>F(k,k[0].toUpperCase()+k.slice(1),'length')),F('notes','Notes','textarea')]},
 workouts:{name:'Workout',fields:[F('date','Date','date',true),F('type','Workout type','select',true,'Walking|Running|Strength training|Cycling|Yoga|Pilates|Swimming|Cardio|Mobility|Other'),F('customType','Custom activity name'),F('minutes','Duration in minutes','integer',true),F('intensity','Intensity','select',true,'Gentle|Moderate|Vigorous|Self-paced'),F('calories','Calories burned (optional estimate)','integer'),F('notes','Notes','textarea')]},
 goals:{name:'Goal',fields:[F('name','Goal name','text',true),F('category','Goal type','select',true,'Weight|Workouts|Distance|Water|Sleep|Consistency|Other'),F('current','Current progress','decimal',true),F('target','Target','decimal',true),F('unit','Unit (sessions, km, days…)'),F('deadline','Target date','date'),F('status','Status','select',true,'Active|Completed|Paused'),F('notes','Notes','textarea')]},
 habits:{name:'Habit',fields:[F('name','Habit name','text',true),F('unit','Short label (optional)'),F('notes','Notes','textarea')]},
 milestones:{name:'Personal milestone',fields:[F('name','Milestone','text',true),F('date','Date','date',true),F('notes','What happened?','textarea')]},
 notes:{name:'Progress note',fields:[F('name','Title','text',true),F('date','Date','date',true),F('confidence','Confidence (1–5)','confidence',true),F('notes','Reflection','textarea',true),F('photoNote','Photo note (description only)','textarea')]}
};
function field(f,r){let v=r?.[f.k]??'',type=f.type;if(type==='weight')v=v?inputWeight(v):'';if(type==='length')v=v?inputLength(v):'';let lab=esc(f.l)+(type==='weight'?' ('+state.settings.weightUnit+')':type==='length'?' ('+state.settings.lengthUnit+')':'');let opts='';if(type==='select')opts='<option value="">Select…</option>'+f.choices.split('|').map(x=>'<option value="'+esc(x)+'" '+(v===x?'selected':'')+'>'+esc(x)+'</option>').join('');let input=type==='textarea'?'<textarea name="'+f.k+'" rows="3">'+esc(v)+'</textarea>':type==='select'?'<select name="'+f.k+'" '+(f.required?'required':'')+'>'+opts+'</select>':'<input name="'+f.k+'" type="'+(['weight','length','integer','decimal','confidence'].includes(type)?'number':type)+'" value="'+esc(v)+'" '+(f.required?'required':'')+' '+(['weight','length','decimal'].includes(type)?'step=".1" min="0"':type==='integer'?'step="1" min="0"':type==='confidence'?'step="1" min="1" max="5"':'')+'>';return '<label class="field '+(type==='textarea'?'wide':'')+'">'+lab+(f.required?' *':'')+input+'</label>'}
function openForm(kind,id=''){let def=defs[kind],r=state.data[kind]?.find(x=>x.id===id);if(!def)return;editing={kind,id};focusBack=document.activeElement;$('#editorTitle').textContent=(id?'Edit ':'Add ')+def.name;$('#fields').innerHTML=def.fields.map(x=>field(x,r||{date:today(),intensity:'Moderate',status:'Active',confidence:3})).join('');$('#formError').hidden=true;$('#editor').showModal();$('#fields input,#fields select')?.focus()}
function closeForm(){if($('#editor').open)$('#editor').close();focusBack?.focus?.()}
function submitForm(e){e.preventDefault();let {kind,id}=editing,raw=Object.fromEntries(new FormData(e.currentTarget)),out={id:id||uid()},err='';for(let f of defs[kind].fields){let v=String(raw[f.k]??'').trim();if(f.required&&!v){err=f.l+' is required.';break}if(f.type==='date'&&v&&!dateOK(v)){err=f.l+' must be a real date.';break}if(f.type==='weight'||f.type==='length'||f.type==='decimal'||f.type==='integer'||f.type==='confidence'){let n=v?(f.type==='weight'?toKg(v):f.type==='length'?toCm(v):num(v,f.type==='confidence'?1:0,100000,f.type==='integer'||f.type==='confidence'?0:1)):0;if(!Number.isFinite(n)||((f.type==='integer'||f.type==='confidence')&&!Number.isInteger(n))){err=f.l+' must be a valid number.';break}out[f.k]=n}else out[f.k]=v.slice(0,f.type==='textarea'?4000:200)}if(!err&&kind==='weights'&&out.kg<=0)err='Weight must be above zero.';if(!err&&kind==='workouts'&&out.minutes<=0)err='Duration must be above zero.';if(!err&&kind==='goals'&&out.target<=0)err='Target must be above zero.';if(!err&&kind==='workouts'&&out.type==='Other'&&out.customType)out.type=out.customType;if(err){$('#formError').textContent=err;$('#formError').hidden=false;return}let arr=state.data[kind],i=arr.findIndex(x=>x.id===id);if(i>=0)arr[i]=out;else arr.push(out);save();closeForm();renderView();toast('Saved '+defs[kind].name.toLowerCase()+'.')}
function exportCSV(kind){let fields={weights:['date','kg','notes'],measurements:['date',...measureKeys,'notes'],workouts:['date','type','minutes','intensity','calories','notes']}[kind];if(!fields)return;csv([fields,...state.data[kind].map(r=>fields.map(k=>r[k]??''))],'HarborNest-Motion-Milestones-'+kind+'.csv')}
function seed(){let base=today(),start=shiftDay(base,-49);state.profile={name:'Sample journey',startKg:78.5,goalKg:72,startDate:start,deadline:shiftDay(base,90)};state.data.weights=[0,7,14,21,28,35,42,49].map((n,i)=>({id:'sample-weight-'+i,date:shiftDay(start,n),kg:[78.5,78.2,77.8,77.9,77.3,76.8,76.6,76.2][i],notes:'Fictional check-in'}));state.data.measurements=[{id:'sample-measure',date:base,waist:84,hips:98,chest:94,arms:29,thighs:54,shoulders:105,notes:'Fictional sample'}];state.data.workouts=Array.from({length:16},(_,i)=>({id:'sample-workout-'+i,date:shiftDay(base,-i*3),type:['Walking','Strength training','Yoga','Cycling'][i%4],customType:'',minutes:25+i%4*10,intensity:'Moderate',calories:0,notes:'Sample session'}));state.data.habits=[{id:'sample-habit-1',name:'Move for 20 minutes',unit:'Movement',notes:''},{id:'sample-habit-2',name:'Stretch',unit:'Recovery',notes:''},{id:'sample-habit-3',name:'Water check-in',unit:'Hydration',notes:''}];state.data.checks=[0,1,2,3,4].flatMap(i=>state.data.habits.slice(0,i%3+1).map(h=>({id:uid(),habitId:h.id,date:shiftDay(weekOf(base),i)})));state.data.goals=[{id:'sample-goal',name:'Move 3 days each week',category:'Workouts',current:2,target:3,unit:'sessions',deadline:'',status:'Active',notes:'A realistic weekly goal.'}];state.data.milestones=[{id:'sample-milestone',name:'Completed my first month',date:shiftDay(base,-20),notes:'Fictional achievement.'}];state.data.notes=[{id:'sample-note',name:'Feeling steadier',date:shiftDay(base,-2),confidence:4,notes:'A fictional reflection about energy and routine.',photoNote:'Morning walking route, described in words.'}]}

function click(e){let b=e.target.closest('button');if(!b)return;if(b.dataset.nav)return navigate(b.dataset.nav);if(b.dataset.profile){navigate('settings');return $('#profileStart')?.focus()}if(b.dataset.add)return openForm(b.dataset.add);if(b.dataset.edit)return openForm(b.dataset.edit,b.dataset.id);if(b.dataset.themeChoice){state.settings.theme=b.dataset.themeChoice;save();appearance();return renderView()}if(b.dataset.print)return window.print();if(b.dataset.csv)return exportCSV(b.dataset.csv);if(b.dataset.week){weekStart=shiftDay(weekStart||weekOf(today()),Number(b.dataset.week));return renderView()}if(b.dataset.check){let arr=state.data.checks,i=arr.findIndex(x=>x.habitId===b.dataset.check&&x.date===b.dataset.date);if(i>=0)arr.splice(i,1);else arr.push({id:uid(),habitId:b.dataset.check,date:b.dataset.date});save();return renderView()}if(b.dataset.delete){let kind=b.dataset.delete,id=b.dataset.id;ask('Delete this record? This cannot be undone.').then(ok=>{if(!ok)return;state.data[kind]=state.data[kind].filter(x=>x.id!==id);if(kind==='habits')state.data.checks=state.data.checks.filter(x=>x.habitId!==id);save();renderView();toast('Record deleted.')});return}if(b.id==='saveProfile'){let start=$('#profileStart').value,goal=$('#profileGoal').value,date=$('#profileDate').value,deadline=$('#profileDeadline').value,startKg=start?toKg(start):0,goalKg=goal?toKg(goal):0;if((start&&(!Number.isFinite(startKg)||startKg<=0))||(goal&&(!Number.isFinite(goalKg)||goalKg<=0))||!dateOK(date)||(deadline&&!dateOK(deadline))){toast('Check weights and dates before saving.');return}state.profile={name:$('#profileName').value.trim().slice(0,60),startKg,goalKg,startDate:date,deadline};save();navigate('dashboard');toast('Starting point saved.');return}if(b.id==='appearanceReset'){let units={weightUnit:state.settings.weightUnit,lengthUnit:state.settings.lengthUnit};state.settings={...structuredClone(defaults),...units};save();appearance();renderView();toast('Default appearance restored.');return}if(b.id==='saveCustomTheme'){let hex=$('#customAccent').value,rgb=[1,3,5].map(i=>parseInt(hex.slice(i,i+2),16)/255),linear=rgb.map(c=>c<=.04045?c/12.92:((c+.055)/1.055)**2.4),lum=.2126*linear[0]+.7152*linear[1]+.0722*linear[2],name='Custom '+(Object.keys(state.settings.customThemes).length+1);state.settings.customThemes[name]={...themes.Ivory,accent:hex,accentText:lum>.179?'#102623':'#ffffff',chart:hex};state.settings.accent=hex;state.settings.theme=name;save();appearance();renderView();toast(name+' saved.');return}if(b.id==='backupBtn'){download(new Blob([JSON.stringify(state,null,2)],{type:'application/json'}),'HarborNest-Motion-Milestones-backup-'+today()+'.json');return}if(b.id==='restoreBtn')return $('#restoreFile').click();if(b.id==='resetBtn'){ask('Erase every local fitness record? Please download a backup first if you need it.').then(ok=>{if(!ok)return;state=blank();if(window.DEMO_MODE)seed();save();appearance();navigate('dashboard');toast('Planner reset.')});return}}
function change(e){let t=e.target,k=t.dataset.setting;if(!k)return;state.settings[k]=k==='contrast'?t.checked:t.value;save();appearance();renderView()}
async function restore(e){let f=e.target.files?.[0];e.target.value='';if(!f)return;try{let x=JSON.parse(await f.text());if(!validState(x))throw Error('Invalid backup format.');if(!await ask('Replace all current records with this backup?'))return;state={version:1,profile:x.profile,settings:{...structuredClone(defaults),...x.settings},data:Object.fromEntries(kinds.map(k=>[k,x.data[k]]))};save();appearance();navigate('dashboard');toast('Backup restored.')}catch(err){toast(err.message||'Could not restore backup.')}}
async function init(){try{db=await openDB();let x=await load();if(x&&validState(x))state={version:1,profile:x.profile,settings:{...structuredClone(defaults),...x.settings},data:Object.fromEntries(kinds.map(k=>[k,x.data[k]]))};else if(window.DEMO_MODE){seed();save()}}catch{document.querySelector('#view').innerHTML='<div class="notice">Browser storage is unavailable. Check storage settings or private mode.</div>';return}if(window.DEMO_MODE)$('#demoBanner').hidden=false;appearance();nav();renderView();document.addEventListener('click',click);document.addEventListener('change',change);document.addEventListener('input',e=>{if(e.target.id!=='listSearch')return;search=e.target.value;clearTimeout(searchTimer);searchTimer=setTimeout(()=>{let host=$('#listContainer');if(!host)return;let container=document.createElement('div'),fn={weight:weightView,measurements:measurementView,workouts:workoutView,notes:notesView}[view];if(!fn)return;container.innerHTML=fn();let next=container.querySelector('#listContainer');if(next)host.replaceChildren(...next.childNodes)},150)});$('#editorForm').addEventListener('submit',submitForm);$('#closeEditor').addEventListener('click',closeForm);$('#cancelEditor').addEventListener('click',closeForm);$('#editor').addEventListener('close',()=>focusBack?.focus?.());$('#confirmNo').addEventListener('click',()=>confirmClose(false));$('#confirmYes').addEventListener('click',()=>confirmClose(true));$('#confirmDialog').addEventListener('cancel',e=>{e.preventDefault();confirmClose(false)});$('#restoreFile').addEventListener('change',restore);$('#quickAdd').addEventListener('click',()=>openForm('workouts'));$('#searchBtn').addEventListener('click',()=>{navigate('workouts');$('#listSearch')?.focus()});$('#menuBtn').addEventListener('click',()=>{let s=$('.sidebar');s.classList.toggle('open');$('#menuBtn').setAttribute('aria-expanded',s.classList.contains('open'))});$('#resetDemo')?.addEventListener('click',()=>{state=blank();seed();save();navigate('dashboard')})}
init();
})();
